name: security-scans
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
env:
  APP_NAME: "${{ github.repository }}"
jobs:
  security-scans:
    name: Veracode Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Veracode CLI - Install
        run: curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Veracode CLI - Autopackager
        run: ./veracode package --source . --output veracode_artifacts --trust

      - name: Veracode SCA - Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.VERACODE_SCA_TOKEN }}
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
          SCA_APP_NAME=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${{ github.repository }}', safe=''))")
          echo "App name encoded: $SCA_APP_NAME"
          curl -sSL https://sca-downloads.veracode.com/ci.sh | sh -s -- scan --allow-dirty --recursive --appname "Juan-Node-Goat" --json sca_results.json --show-cli

      - name: Veracode SCA - Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: sca_results.json

      - name: Veracode Pipeline Scan - Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.21
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: veracode_artifacts/*.zip
          fail_build: false

      - name: Veracode Upload & SAST - Scan
        uses: veracode/veracode-uploadandscan-action@0.2.11
        with:
          appname: "Juan-Node-Goat"
          createprofile: true
          filepath: veracode_artifacts/*.zip
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createsandbox: false
          deleteincompletescan: 1
